# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inew_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1207, 708)
        MainWindow.setStyleSheet("width:inherit;\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border-image: url(blurriver.jpg);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 9, 1261, 71))
        self.frame.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border-image:none;\n"
"background-color: rgba(168, 168, 168, 100);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 1221, 31))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255,20);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Source Sans Pro ExtraLight\";\n"
"margin-left:30px;\n"
"border-radius:0px;")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(210, 90, 1061, 611))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgba(74, 74, 74, 50);\n"
"\n"
"border-image:none;")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tabWidgetPage1)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 40, 471, 331))
        self.graphicsView_3.setStyleSheet("background-color: rgb(90, 86, 73,150);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.tabWidgetPage1)
        self.graphicsView_6.setGeometry(QtCore.QRect(20, 400, 251, 181))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.tabWidgetPage1)
        self.graphicsView_7.setGeometry(QtCore.QRect(350, 400, 251, 181))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.tabWidgetPage1)
        self.graphicsView_9.setGeometry(QtCore.QRect(670, 400, 251, 181))
        self.graphicsView_9.setStyleSheet("")
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.label_20 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_20.setGeometry(QtCore.QRect(100, 10, 291, 31))
        self.label_20.setStyleSheet("QLabel{ \n"
"    color: rgb(216, 216, 216);\n"
"\n"
"    font: 16pt \"Sitka Small\";\n"
"}\n"
"\n"
"")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_21.setGeometry(QtCore.QRect(110, 380, 71, 16))
        self.label_21.setStyleSheet("color: rgb(216, 216, 216);\n"
"border-radius:3px;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_22.setGeometry(QtCore.QRect(420, 380, 71, 16))
        self.label_22.setStyleSheet("color: rgb(216, 216, 216);\n"
"border-radius:3px;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_23.setGeometry(QtCore.QRect(750, 380, 71, 16))
        self.label_23.setStyleSheet("color: rgb(216, 216, 216);\n"
"border-radius:3px;")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.graphicsView_10 = QtWidgets.QGraphicsView(self.tabWidgetPage1)
        self.graphicsView_10.setGeometry(QtCore.QRect(480, 40, 491, 331))
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.frame_3 = QtWidgets.QFrame(self.tabWidgetPage2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1061, 591))
        self.frame_3.setStyleSheet("\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(520, 0, 231, 41))
        self.label_17.setStyleSheet("font: 75 18pt \"Source Sans Pro ExtraLight\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.frame_3)
        self.graphicsView_4.setGeometry(QtCore.QRect(310, 41, 671, 341))
        self.graphicsView_4.setStyleSheet("background-color: rgb(118, 118, 118);\n"
"border-radius:10px;")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.frame_3)
        self.graphicsView_5.setGeometry(QtCore.QRect(10, 400, 301, 181))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 10, 271, 22))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(70, 370, 171, 31))
        self.label_33.setStyleSheet("font: 75 18pt \"Source Sans Pro ExtraLight\";")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_3)
        self.label_34.setGeometry(QtCore.QRect(320, 500, 81, 51))
        self.label_34.setStyleSheet("font: 34pt \"Source Sans Pro ExtraLight\";\n"
"")
        self.label_34.setObjectName("label_34")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 271, 296))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:7px;")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout.addWidget(self.lineEdit_18)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:7px;")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_2.addWidget(self.lineEdit_19)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_20.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:7px;")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_3.addWidget(self.lineEdit_20)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_4.addWidget(self.label_30)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:7px;")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_4.addWidget(self.lineEdit_21)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget)
        self.label_31.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_5.addWidget(self.label_31)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_22.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:7px;")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_5.addWidget(self.lineEdit_22)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        self.label_32.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_23.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:7px;")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_6.addWidget(self.lineEdit_23)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton.setGeometry(QtCore.QRect(380, 410, 91, 17))
        self.radioButton.setStyleSheet("border-radius:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 255);\n"
"")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_2.setGeometry(QtCore.QRect(500, 410, 101, 17))
        self.radioButton_2.setStyleSheet("border-radius:7px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 127);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(410, 440, 501, 121))
        self.frame_4.setStyleSheet("background-color: rgb(38, 255, 212,255);\n"
"border-radius: 10px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 214, 64))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_48 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_9.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_9.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_9.addWidget(self.label_50)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_8.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_8.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_8.addWidget(self.lineEdit_8)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_15.setGeometry(QtCore.QRect(90, 310, 51, 21))
        self.lineEdit_15.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_5)
        self.graphicsView.setGeometry(QtCore.QRect(200, 70, 521, 411))
        self.graphicsView.setStyleSheet("background-color:rgb(2, 175, 255);")
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphicsView.setLineWidth(2)
        self.graphicsView.setMidLineWidth(1)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.Dense2Pattern)
        self.graphicsView.setBackgroundBrush(brush)
        self.graphicsView.setObjectName("graphicsView")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_14.setGeometry(QtCore.QRect(90, 250, 51, 21))
        self.lineEdit_14.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 181, 20))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-align: center;")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 190, 51, 21))
        self.lineEdit_2.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_16.setGeometry(QtCore.QRect(90, 370, 51, 21))
        self.lineEdit_16.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.comboBox = QtWidgets.QComboBox(self.tab_5)
        self.comboBox.setEnabled(False)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 261, 22))
        self.comboBox.setStyleSheet("border-radius: 8px;\n"
"background-color: rgb(107, 107, 107);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_17.setGeometry(QtCore.QRect(90, 430, 51, 21))
        self.lineEdit_17.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 181, 20))
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 250, 51, 21))
        self.lineEdit_3.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(10, 340, 181, 20))
        self.label_8.setObjectName("label_8")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_13.setGeometry(QtCore.QRect(90, 190, 51, 21))
        self.lineEdit_13.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_12.setGeometry(QtCore.QRect(90, 120, 51, 21))
        self.lineEdit_12.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setGeometry(QtCore.QRect(10, 120, 51, 21))
        self.lineEdit.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 171, 20))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 370, 51, 21))
        self.lineEdit_5.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 430, 51, 21))
        self.lineEdit_11.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(10, 400, 181, 20))
        self.label_18.setObjectName("label_18")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 310, 51, 21))
        self.lineEdit_4.setStyleSheet("background-color :rgb(232, 232, 232);\n"
"border-radius: 8px")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.listWidget = QtWidgets.QListWidget(self.tab_5)
        self.listWidget.setGeometry(QtCore.QRect(720, 40, 261, 471))
        self.listWidget.setStyleSheet("background-color: rgba(223, 223, 223,150);")
        self.listWidget.setObjectName("listWidget")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(10, 280, 181, 20))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(290, 20, 411, 31))
        self.label_3.setStyleSheet("font: 75 18pt \"Source Sans Pro ExtraLight\";\n"
"background-color: rgb(0, 170, 127);\n"
"opacity: 0.1;\n"
"border-radius:5px;")
        self.label_3.setObjectName("label_3")
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        self.label_35.setGeometry(QtCore.QRect(10, 500, 171, 51))
        self.label_35.setStyleSheet("font: 34pt \"Source Sans Pro ExtraLight\";\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius:5px;")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_5)
        self.label_36.setGeometry(QtCore.QRect(30, 480, 131, 16))
        self.label_36.setObjectName("label_36")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_3.setGeometry(QtCore.QRect(270, 490, 91, 17))
        self.radioButton_3.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:7px;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_4.setGeometry(QtCore.QRect(390, 490, 101, 17))
        self.radioButton_4.setStyleSheet("border-radius:7px;\n"
"background-color: rgb(255, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 40, 631, 331))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 380, 141, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 460, 141, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(280, 380, 141, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(280, 460, 141, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(500, 380, 141, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(710, 380, 141, 16))
        self.label_14.setObjectName("label_14")
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setGeometry(QtCore.QRect(710, 460, 141, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setGeometry(QtCore.QRect(10, 400, 131, 41))
        self.label_38.setStyleSheet("font: 34pt \"Source Sans Pro ExtraLight\";")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab)
        self.label_39.setGeometry(QtCore.QRect(10, 480, 131, 41))
        self.label_39.setStyleSheet("font: 34pt \"Source Sans Pro ExtraLight\";")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab)
        self.label_40.setGeometry(QtCore.QRect(280, 400, 131, 41))
        self.label_40.setStyleSheet("font: 34pt \"Source Sans Pro ExtraLight\";")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab)
        self.label_41.setGeometry(QtCore.QRect(280, 480, 131, 41))
        self.label_41.setStyleSheet("font: 34pt \"Source Sans Pro ExtraLight\";")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab)
        self.label_42.setGeometry(QtCore.QRect(500, 400, 131, 41))
        self.label_42.setStyleSheet("font: 34pt \"Source Sans Pro ExtraLight\";")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab)
        self.label_43.setGeometry(QtCore.QRect(710, 400, 261, 41))
        self.label_43.setStyleSheet("font: 16pt \"Source Sans Pro ExtraLight\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setGeometry(QtCore.QRect(710, 480, 261, 41))
        self.label_44.setStyleSheet("font: 18pt \"Source Sans Pro ExtraLight\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(10, 0, 641, 31))
        self.label_45.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(222, 222, 222);")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.tab)
        self.label_46.setGeometry(QtCore.QRect(670, 190, 111, 21))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab)
        self.label_47.setGeometry(QtCore.QRect(670, 210, 81, 51))
        self.label_47.setStyleSheet("font: 34pt \"Source Sans Pro ExtraLight\";")
        self.label_47.setObjectName("label_47")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(670, 20, 131, 151))
        self.groupBox_3.setStyleSheet("background-color: rgba(18, 18, 18, 200);\n"
"border-radius:2px;")
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 20, 131, 131))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_10.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 85, 0);\n"
"")
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_10.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_10.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_10.addWidget(self.radioButton_8)
        self.listWidget_3 = QtWidgets.QListWidget(self.tab)
        self.listWidget_3.setGeometry(QtCore.QRect(810, 20, 181, 261))
        self.listWidget_3.setStyleSheet("background-color: rgba(199, 228, 255, 100);")
        self.listWidget_3.setObjectName("listWidget_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_5 = QtWidgets.QFrame(self.tab_2)
        self.frame_5.setGeometry(QtCore.QRect(20, 30, 961, 471))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_51 = QtWidgets.QLabel(self.frame_5)
        self.label_51.setGeometry(QtCore.QRect(20, 20, 47, 31))
        self.label_51.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.label_51.setObjectName("label_51")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_9.setGeometry(QtCore.QRect(60, 30, 431, 20))
        self.lineEdit_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_9.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(540, 30, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(9)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(98, 98, 98);\n"
"border-radius:5px;\n"
"border-image:none;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    \n"
"    background-color: rgb(255, 49, 200);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(0, 170, 255);\n"
"padding-top :2px;\n"
"}")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 80, 921, 371))
        self.groupBox_2.setStyleSheet("background-color: rgb(166, 166, 166);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_52 = QtWidgets.QLabel(self.groupBox_2)
        self.label_52.setGeometry(QtCore.QRect(20, 50, 101, 21))
        self.label_52.setStyleSheet("border-image:none;")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox_2)
        self.label_53.setGeometry(QtCore.QRect(140, 50, 171, 21))
        self.label_53.setStyleSheet("border-image:none;")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.groupBox_2)
        self.label_54.setGeometry(QtCore.QRect(20, 90, 101, 21))
        self.label_54.setStyleSheet("border-image:none;")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.groupBox_2)
        self.label_55.setGeometry(QtCore.QRect(140, 90, 171, 21))
        self.label_55.setStyleSheet("border-image:none;")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_2)
        self.label_56.setGeometry(QtCore.QRect(20, 130, 101, 21))
        self.label_56.setStyleSheet("border-image:none;")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.groupBox_2)
        self.label_57.setGeometry(QtCore.QRect(140, 130, 171, 21))
        self.label_57.setStyleSheet("border-image:none;")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_2)
        self.label_58.setGeometry(QtCore.QRect(20, 170, 101, 21))
        self.label_58.setStyleSheet("border-image:none;")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.groupBox_2)
        self.label_59.setGeometry(QtCore.QRect(20, 210, 101, 21))
        self.label_59.setStyleSheet("border-image:none;")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox_2)
        self.label_60.setGeometry(QtCore.QRect(140, 170, 171, 21))
        self.label_60.setStyleSheet("border-image:none;")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.groupBox_2)
        self.label_61.setGeometry(QtCore.QRect(140, 210, 171, 21))
        self.label_61.setStyleSheet("border-image:none;")
        self.label_61.setObjectName("label_61")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 320, 75, 23))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgb(63, 63, 63);\n"
"border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"border-image:none;\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"background-color: qlineargradient(spread:reflect, x1:0.426, y1:0.0113636, x2:0.419, y2:0.550773, stop:0.0454545 rgba(138, 138, 138, 225), stop:0.414773 rgba(146, 146, 146, 255), stop:0.710227 rgba(156, 156, 156, 255), stop:0.982955 rgba(162, 162, 162, 255));\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(790, 320, 75, 23))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(63, 63, 63);\n"
"border-radius: 10px;\n"
"border-image:none;\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"background-color:rgb(170, 0, 0)\n"
"}")
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 320, 621, 31))
        self.lineEdit_10.setStyleSheet("QLineEdit{background-color: qlineargradient(spread:reflect, x1:0.426, y1:0.0113636, x2:0.419, y2:0.550773, stop:0.0454545 rgba(138, 138, 138, 225), stop:0.414773 rgba(146, 146, 146, 255), stop:0.710227 rgba(156, 156, 156, 255), stop:0.982955 rgba(162, 162, 162, 255));\n"
"font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(180, 180, 180);\n"
"border-image:none;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"font: 75  16pt \"Nirmala UI Semilight\";\n"
"color:rgb(255, 255, 255);\n"
"    background-color: rgb(120, 120, 120);\n"
"}")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 85, 191, 41))
        self.label_15.setStyleSheet("background-color: rgb(111, 111, 111);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Source Sans Pro ExtraLight\";\n"
"\n"
"\n"
"border-image:none;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_15.setObjectName("label_15")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 120, 191, 191))
        self.listWidget_2.setStyleSheet("border-image:none;\n"
"background-color: rgba(179, 179, 179, 100);")
        self.listWidget_2.setIconSize(QtCore.QSize(75, 55))
        self.listWidget_2.setObjectName("listWidget_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 320, 191, 121))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("background-color: rgb(193, 193, 193,150);\n"
"border-image:none;\n"
"border-color: rgb(3, 3, 3);")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 171, 20))
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.label_19.setObjectName("label_19")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 171, 21))
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.label_16.setObjectName("label_16")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 171, 21))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1207, 0))
        self.menubar.setObjectName("menubar")
        self.menuFILE = QtWidgets.QMenu(self.menubar)
        self.menuFILE.setObjectName("menuFILE")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpload_File = QtWidgets.QAction(MainWindow)
        self.actionUpload_File.setObjectName("actionUpload_File")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menuFILE.addAction(self.actionUpload_File)
        self.menuFILE.addSeparator()
        self.menuFILE.addAction(self.action_Exit)
        self.menubar.addAction(self.menuFILE.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.comboBox_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Information Intervention"))
        self.label.setText(_translate("MainWindow", "SCHOOL NAME :"))
        self.label_20.setText(_translate("MainWindow", "CLASS NAME "))
        self.label_21.setText(_translate("MainWindow", "TERM ONE "))
        self.label_22.setText(_translate("MainWindow", "TERM TWO"))
        self.label_23.setText(_translate("MainWindow", "TERM THREE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "DashBoard"))
        self.label_17.setText(_translate("MainWindow", "CLASS PERFORMANCE "))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Yearly"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Term One"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Term Two"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Term Three"))
        self.label_33.setText(_translate("MainWindow", "Total Percentage"))
        self.label_34.setText(_translate("MainWindow", "5%"))
        self.radioButton.setText(_translate("MainWindow", "Bar Graph"))
        self.radioButton_2.setText(_translate("MainWindow", "Scatter Plot"))
        self.label_48.setText(_translate("MainWindow", "Total Passed:"))
        self.label_49.setText(_translate("MainWindow", "Total Failed :"))
        self.label_50.setText(_translate("MainWindow", "Avarage Pass Mark:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "Class Performance "))
        self.lineEdit_15.setText(_translate("MainWindow", "0"))
        self.lineEdit_14.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.lineEdit_16.setText(_translate("MainWindow", "0"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Term One"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Term Two"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Term Three"))
        self.lineEdit_17.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.lineEdit_3.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.lineEdit_13.setText(_translate("MainWindow", "0"))
        self.lineEdit_12.setText(_translate("MainWindow", "0"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.lineEdit_5.setText(_translate("MainWindow", "0"))
        self.lineEdit_11.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "LEARNER NAME :"))
        self.label_36.setText(_translate("MainWindow", "TERM AVAREGE"))
        self.radioButton_3.setText(_translate("MainWindow", "Bar Graph"))
        self.radioButton_4.setText(_translate("MainWindow", "Scatter Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Learner Performance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Comparison "))
        self.label_9.setText(_translate("MainWindow", "MEAN"))
        self.label_10.setText(_translate("MainWindow", "MODE"))
        self.label_11.setText(_translate("MainWindow", "Deviance"))
        self.label_12.setText(_translate("MainWindow", "MIN"))
        self.label_13.setText(_translate("MainWindow", "MAX"))
        self.label_14.setText(_translate("MainWindow", "TOP PERFORMER"))
        self.label_37.setText(_translate("MainWindow", "LOW PERFORMER"))
        self.label_38.setText(_translate("MainWindow", "6%"))
        self.label_39.setText(_translate("MainWindow", "7%"))
        self.label_40.setText(_translate("MainWindow", "4.78"))
        self.label_41.setText(_translate("MainWindow", "45"))
        self.label_42.setText(_translate("MainWindow", "89"))
        self.label_43.setText(_translate("MainWindow", "akhona"))
        self.label_44.setText(_translate("MainWindow", "thina "))
        self.label_45.setText(_translate("MainWindow", "TASK MARKS DISTRIBUTION"))
        self.label_46.setText(_translate("MainWindow", "PASS RATE:"))
        self.label_47.setText(_translate("MainWindow", "67%"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Term Selection "))
        self.radioButton_5.setText(_translate("MainWindow", "Term One "))
        self.radioButton_6.setText(_translate("MainWindow", "Term Two"))
        self.radioButton_7.setText(_translate("MainWindow", "Term Three"))
        self.radioButton_8.setText(_translate("MainWindow", "Term Four"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Task Performance"))
        self.label_51.setText(_translate("MainWindow", "File:"))
        self.pushButton.setText(_translate("MainWindow", "Browser"))
        self.label_52.setText(_translate("MainWindow", "Teacher :"))
        self.label_53.setText(_translate("MainWindow", "TextLabel"))
        self.label_54.setText(_translate("MainWindow", "Subject:"))
        self.label_55.setText(_translate("MainWindow", "TextLabel"))
        self.label_56.setText(_translate("MainWindow", "Class :"))
        self.label_57.setText(_translate("MainWindow", "TextLabel"))
        self.label_58.setText(_translate("MainWindow", "Number of Learners"))
        self.label_59.setText(_translate("MainWindow", "School Name"))
        self.label_60.setText(_translate("MainWindow", "TextLabel"))
        self.label_61.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.lineEdit_10.setText(_translate("MainWindow", "If the information provided is correct please continue by clicking correct,then submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "File Upload"))
        self.label_15.setText(_translate("MainWindow", "CLASSES"))
        self.label_19.setText(_translate("MainWindow", "NUMBER OF LEARNERS :"))
        self.label_16.setText(_translate("MainWindow", "SUBJECT: "))
        self.label_2.setText(_translate("MainWindow", "CLASS :"))
        self.menuFILE.setTitle(_translate("MainWindow", "FILE"))
        self.actionUpload_File.setText(_translate("MainWindow", "Upload the xls or xlsx file here"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))


